### PR TITLE
Update readme with specific esp32 version

### PR DESCRIPTION
**Pull request by francip**
Update the readme for the OpenGlass firmware with the specific version of Expressif Arduino esp32 platform to install

### CODE REVIEW

**Comment by francip** [comment]
```
C:\Users\Franci Penov\src\OpenGlass\firmware>arduino-cli compile -u -p COM6 -b esp32:esp32:nora_w10:PSRAM=opi
Sketch uses 979353 bytes (74%) of program storage space. Maximum is 1310720 bytes.
Global variables use 48788 bytes (14%) of dynamic memory, leaving 278892 bytes for local variables. Maximum is 327680 bytes.
esptool.py v4.5.1
Serial port COM6
Connecting...
Chip is ESP32-S3 (revision v0.2)
Features: WiFi, BLE
Crystal is 40MHz
MAC: 74:4d:bd:95:bb:88
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
Configuring flash size...
Flash will be erased from 0x00000000 to 0x00003fff...
Flash will be erased from 0x00008000 to 0x00008fff...
Flash will be erased from 0x0000e000 to 0x0000ffff...
Flash will be erased from 0x00010000 to 0x000fffff...
Compressed 15104 bytes to 10430...
Writing at 0x00000000... (100 %)
Wrote 15104 bytes (10430 compressed) at 0x00000000 in 0.3 seconds (effective 438.4 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 146...
Writing at 0x00008000... (100 %)
Wrote 3072 bytes (146 compressed) at 0x00008000 in 0.1 seconds (effective 316.3 kbit/s)...
Hash of data verified.
Compressed 8192 bytes to 47...
Writing at 0x0000e000... (100 %)
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.1 seconds (effective 530.6 kbit/s)...
Hash of data verified.
Compressed 979712 bytes to 593853...
Writing at 0x00010000... (2 %)
Writing at 0x0001b928... (5 %)
Writing at 0x00028def... (8 %)
Writing at 0x000344cd... (10 %)
Writing at 0x00041fed... (13 %)
Writing at 0x00047af2... (16 %)
Writing at 0x0004d536... (18 %)
Writing at 0x00052ee0... (21 %)
Writing at 0x000588e9... (24 %)
Writing at 0x0005e3a2... (27 %)
Writing at 0x00063ae1... (29 %)
Writing at 0x00068cfa... (32 %)
Writing at 0x0006e068... (35 %)
Writing at 0x000733ce... (37 %)
Writing at 0x00078427... (40 %)
Writing at 0x0007e3c9... (43 %)
Writing at 0x00084067... (45 %)
Writing at 0x00089994... (48 %)
Writing at 0x0008f2ef... (51 %)
Writing at 0x00094a88... (54 %)
Writing at 0x0009a113... (56 %)
Writing at 0x000a0c9c... (59 %)
Writing at 0x000a6720... (62 %)
Writing at 0x000ac09d... (64 %)
Writing at 0x000b28e8... (67 %)
Writing at 0x000b8235... (70 %)
Writing at 0x000bd866... (72 %)
Writing at 0x000c2ea7... (75 %)
Writing at 0x000c8679... (78 %)
Writing at 0x000cdfd5... (81 %)
Writing at 0x000d418c... (83 %)
Writing at 0x000dc4f1... (86 %)
Writing at 0x000e4d8d... (89 %)
Writing at 0x000ed39b... (91 %)
Writing at 0x000f26f4... (94 %)
Writing at 0x000f7ef8... (97 %)
Writing at 0x000fd9f6... (100 %)
Wrote 979712 bytes (593853 compressed) at 0x00010000 in 7.6 seconds (effective 1026.1 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

Used library      Version Path
I2S               1.0     C:\Users\Franci Penov\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.17\libraries\I2S
ESP32 BLE Arduino 2.0.0   C:\Users\Franci Penov\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.17\libraries\BLE

Used platform Version Path
esp32:esp32   2.0.17  C:\Users\Franci Penov\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.17
```

**Review by WeldFire — APPROVED** [review]
I was able to build with this change as the latest (3.0.0 at the time of writing) is missing the I2S.h header.

**Comment by francip** [comment]
@WeldFire can you merge, as I don't have permissions. Or maybe @Bentlybro or @kodjima33?

**Comment by kowyo** [comment]
I ran the command: `arduino-cli core install esp32:esp32@2.0.17` and got the following output:
```warp
Error during install: Platform 'esp32:esp32@2.0.17' not found: required version 2.0.17 not found for platform esp32:esp32
```
How do I fix this?

**Pull request merged**
